---
controller_hosts:
  - name: localhost
    inventory: Localhost_inventory
    variables:
      ansible_connection: local
      ansible_python_interpreter: '{{ ansible_playbook_python }}'

  - name: "{{ controller_hostname }}"
    inventory: Controllers
    enabled: true
    state: present
    variables:
      ansible_connection: local
  - name: 10.242.42.143
    inventory: AAP Hosts
    variables:
      ansible_connection: ssh
      ansible_ssh_user: awx
      ansible_ssh_pass: password
  - name: localhost
    inventory: Blank (localhost only)
    variables:
      ansible_connection: local

...
